sudo: false
language: node_js
node_js:
  - "node"
cache:
  directories:
    - $HOME/.yarn-cache
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run lint
  - yarn run coverage
  - yarn run build:dev
  - yarn run build:prod
  - yarn run build:docs
after:
  - yarn test
